Updated dependencies, switch to ESM and require node 12.20
vercel/ms pull request #162
Opened 2021-08-13 10:12 UTC by jimmywarting

Closes #159 

Personally i don't see any reason for converting it to TypeScript. JSDoc works just as well for providing typing support.
...and dose not require compiling so importing it to Deno with http import gives you typing with ease as well as making it possible to import it using http loader from browsers and nodes new HTTP loader

2021-08-13 15:46 UTC, mrmckeb requested changes
The changes in this PR unfortunately mean that some developers would no longer be able to use this library, as we're no longer shipping a CJS module.

For example, with this code:
```js
const ms = require("ms");
```

Users will see the following:
```
require() of ES modules is not supported.
```

I (personally) feel that TypeScript might actually be a better solution here as we could use it to generate ES and CJS modules, and also emit types.

2021-08-13 17:39 UTC, jimmywarting commented
> I (personally) feel that TypeScript might actually be a better solution here as we could use it to generate ES and CJS modules, and also emit types.

You can still do that with allowJS + checkJS + plus you would not need to waste time compiling.

2021-08-16 16:32 UTC, mrmckeb commented
Hi @jimmywarting, sorry for the slow response.

> They can still import it using the async syntax import('ms')

I've discussed this with a few colleagues, and we still think we should ship ESM and CJS:
- `import()` would require some users to reimplement `ms`, which we can avoid by shipping CJS alongside ESM.
- It's fairly standard for libraries to ship and support both formats today, and this is what users will expect.

> You can still do that with allowJS + checkJS + plus you would not need to waste time compiling.

I like the approach, and use it myself sometime for small utilities, but this is only good internally. TypeScript would allow us to ship types - which we don't do today - saving over [700,000 additional package downloads a week](https://www.npmjs.com/package/@types/ms). That's a win for our users, and the environment :)

The cost of compiling this to CJS and ESM with TypeScript is around 2.8s on my M1, so I don't think it's a notable cost here.

Are you OK to make these changes? No pressure if not! I can take a look at this over the next few days.

2021-08-16 16:35 UTC, mrmckeb commented on package.json
> +    "node": ">=12.20"
Quick question on this, why `12.20` specifically?

2021-08-16 18:46 UTC, jimmywarting commented on package.json
> +    "node": ">=12.20"
sindresorhus is converting all his 1k packages to ESM only https://github.com/sindresorhus/meta/discussions/15
in normal situations you can use 12.17 - that is the lowest support for ESM

12.20 is for those who mostly use `node:` prefix to import eg: `import fs from 'node:fs'`

2021-08-16 19:05 UTC, jimmywarting commented
> Are you OK to make these changes? No pressure if not! I can take a look at this over the next few days.

If you want typescript, then fine by me. The outcome is the same for me. just don't expect any more PR from me. 
Love typing but hate the syntax and not being able to run things natively in browser... still prefer jsdoc over ts and non bundled files for easier code spliting.
Lot's of Typescript project unfortunately bundle everything together...

> I like the approach, and use it myself sometime for small utilities, but this is only good internally. TypeScript would allow us to ship types - which we don't do today - saving over 700,000 additional package downloads a week. That's a win for our users, and the environment :)

You can still utilize typescript to generate d.ts from vanilla js + jsdoc
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html 

---

I use typescript myself (but only for it's typing support - using jsdoc) I never use the typescript syntax.
best part of it is that you can 
- import vanila js directly in the browser and also to Deno
- Ship typing support to Deno using the same browser based files without loading extra d.ts files
- and you could also use node's new http loader to import files without npm

i don't like build tools as much as everyone other typescript user dose. 
i prefer buildless projects and files that can be imported in all environments (Deno, Browser & Nodes http loader) for best cross compatible code

2021-08-16 19:25 UTC, jimmywarting commented
infact if you try out the [Deno plugin](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) for VSCode and import this vanila js library written in ESM and JSDoc 

https://cdn.jsdelivr.net/gh/jimmywarting/native-file-system-adapter/src/es6.js

![image](https://user-images.githubusercontent.com/1148376/129617927-d59111d4-c3c4-48e9-9978-0cc8afe10fcc.png)
![image](https://user-images.githubusercontent.com/1148376/129618432-009dd20e-95b4-484e-9197-a199ce3bf77f.png)

then you do get typing support and you won't need any extra `d.ts` files or any NPM package manager
Pretty sweet if you ask me

2021-08-17 18:26 UTC, mrmckeb commented
Thanks for your time on this @jimmywarting. I'll make the changes as discussed, I've just opened #163 for early feedback and hope to ship this within the next week.

2021-08-17 18:26 UTC, closed without merging